/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import java.util.ArrayList;
import patientmanagementsystem.doctor_system.Appointment;
import patientmanagementsystem.doctor_system.Doctor;
import patientmanagementsystem.doctor_system.Prescription;
import patientmanagementsystem.patient_system.Patient;
import patientmanagementsystem.patient_system.PatientHistory;

/**
 *
 * @author Dyn
 */
public class ViewPatientHistory extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientHistory
     */
    
    private PatientHistory patientHistory;
    
    private Patient patient;
    private PatientSystemMain patientMain;
    
    private Doctor doctor;
    private DoctorSystemMain doctorMain;
    
    public ViewPatientHistory(Patient _patient, PatientSystemMain _patientMain) {
        this.patient = _patient;
        this.patientMain = _patientMain;
        initComponents();
        
        this.patientHistory = new PatientHistory(patient);
        this.patientHistory.initPatientHistory();
        
        showPatientHistory();
        
    }
    
    public ViewPatientHistory(Doctor _doctor, DoctorSystemMain _doctorMain) {
        this.doctor = _doctor;
        this.doctorMain = _doctorMain;
        initComponents();
    }
    
    public void showPatientHistory() {
        
        jTextArea1.setText("");
        
        ArrayList<Appointment> appointments = new ArrayList<>();
        
        appointments = patientHistory.Appointments().getAppointments();
        
        if ( appointments.size() > 0 ) {
            for ( Appointment a : appointments ) {
                jTextArea1.append(a.getPatientFullname() + "\n"
                + "Dr. " + a.getDoctor() + "\n"
                + "Date : " + a.getDate() + "\n"
                + "Notes : " + a.getNotes() + "\n\n");
            }
        }
        
        jTextArea2.setText("");
        
        ArrayList<Prescription> prescriptions = new ArrayList<>();
        
        prescriptions = this.patientHistory.Prescriptions().getPrescriptions();
        
        if ( prescriptions.size() > 0 ) {
            for ( Prescription p : prescriptions ) {
                jTextArea2.append("Medicine : " + p.getMedicine() + "\n"
                + "Dosage : " + p.getDosage() + "\n\n");
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Patient History");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setText("Appointments : ");

        jLabel3.setText("Prescriptions : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(0, 92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
