/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Component;
import java.awt.Container;
import javax.swing.JTextField;
import panels.AdminSystemMain;
import panels.CreateAccountPanel;
import panels.DoctorSystemMain;
import panels.LogInPanel;
import panels.PanelType;
import static panels.PanelType.ADMIN_MAIN;
import static panels.PanelType.CREATE_ACCOUNT;
import static panels.PanelType.DOCTOR_MAIN;
import static panels.PanelType.LOG_IN;
import panels.PatientSystemMain;
import panels.SecretarySystemMain;
import patientmanagementsystem.User;
import patientmanagementsystem.admin_system.Administrator;
import patientmanagementsystem.admin_system.DoctorRatingsPanel;
import patientmanagementsystem.admin_system.EditDoctorPanel;
import patientmanagementsystem.doctor_system.Doctor;
import patientmanagementsystem.patient_system.Patient;
import patientmanagementsystem.secretary_system.Secretary;
import utils.Files;

/**
 *
 * @author djs85
 */
public class ViewMain extends javax.swing.JFrame {

    /**
     * Creates new form ViewMain
     */
    
    // panels
    private CreateAccountPanel createAccountPanel;
    private AdminSystemMain adminSystemMain;
    private DoctorSystemMain doctorSystemMain;
    private PatientSystemMain patientSystemMain;
    private LogInPanel logInPanel;
    private EditDoctorPanel editDoctorPanel;
    private DoctorRatingsPanel doctorRatingsPanel;
    private SecretarySystemMain secretarySystemMain;
    
    
    protected User loggedInUser;
    
    protected Administrator loggedInAdmin;
    protected Patient loggedInPatient;
    protected Secretary loggedInSec;
    protected Doctor loggedInDoctor;
    
    // ViewMain class is the main JFrame which is responsible for each users
    // home panel.
    
    public ViewMain() {
        
        Files.initPaths(); // very important for filepaths!!!
        initComponents();
        
        this.setBounds(100, 100, 600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PMS Home");

        jButton5.setText("Create Account");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Log In");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(247, 247, 247)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.setPanel(CREATE_ACCOUNT);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setPanel(LOG_IN);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMain().setVisible(true);
            }
        });
    }

    // sets the panel and redraws the frame. 
    public void setPanel(PanelType _panelType) {
        
        switch (_panelType) {
            
            case ADMIN_MAIN:
                
                if ( adminSystemMain == null ) {
                    adminSystemMain = new AdminSystemMain(this, loggedInAdmin);
                    setContentPane(adminSystemMain);
                } else {
                    setContentPane(adminSystemMain);
                }
                
                break;
                
            case DOCTOR_MAIN:
                
                if ( doctorSystemMain == null ) {
                    doctorSystemMain = new DoctorSystemMain(this, loggedInDoctor);
                    setContentPane(doctorSystemMain);
                } else {
                    setContentPane(doctorSystemMain);
                }
                
                break;
                
            case CREATE_ACCOUNT:
                
                if ( createAccountPanel == null ) {
                    createAccountPanel = new CreateAccountPanel(this);
                    setContentPane(createAccountPanel);
                } else {
                    setContentPane(createAccountPanel);
                }
                
                break;
                
            case LOG_IN:
                
                if ( logInPanel == null ) {
                    logInPanel = new LogInPanel(this);
                    setContentPane(logInPanel);
                } else {
                    setContentPane(logInPanel);
                }
                
                break;
                
            case PATIENT_MAIN:
                
                if ( patientSystemMain == null ) {
                    patientSystemMain = new PatientSystemMain(this, loggedInPatient);
                    setContentPane(patientSystemMain);
                } else {
                    setContentPane(patientSystemMain);
                }
                
                break;
                
            case SEC_MAIN:
                if ( secretarySystemMain == null ) {
                    secretarySystemMain = new SecretarySystemMain(this, loggedInSec);
                    setContentPane(secretarySystemMain);
                } else {
                    setContentPane(secretarySystemMain);
                }
                
                break;
                
            default:
                break;
        
        }
        
        this.repaint();
        this.revalidate();
    
    }
    
    // finds all input fields on a panel and clears them.
    public void clearFields() {
        
        Container container = this.getContentPane();
        
        for ( Component c : container.getComponents() ) {
            if ( c instanceof JTextField ) {
                ((JTextField) c).setText(null);
            } 
        }
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    // setLoggedIn?????? sets the type of user for the session.
    public void setLoggedInPatient(Patient patient) {
        this.loggedInPatient = patient;
    }
    
    public void setLoggedInAdmin(Administrator admin) {
        this.loggedInAdmin = admin;
    }
    
    public void setLoggedInDoctor(Doctor doctor) {
        this.loggedInDoctor = doctor;
    }

    public void setLoggedInSecretary(Secretary secretary) {
        this.loggedInSec = secretary;
    }
    
    public User getUser() {
        return this.loggedInUser;
    }
}
